In [557]:
import itertools
import math
import re

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import dynet as dy

LENGTH = 8
PATTERN = np.array([1,0,1])
FILTER_LENGTH = len(PATTERN)

In [559]:
binary_arrays = np.array(list(itertools.product([0,1], repeat=LENGTH)))

get_number_of_occur = lambda test_list: len([PATTERN for idx in range(len(test_list)-len(PATTERN)+1) if (test_list[idx : idx + len(PATTERN)] == PATTERN).all()])
occurences_arrays = np.array(list(map(get_number_of_occur, binary_arrays)))
print(occurences_arrays)

# print(''.join(list(map(str,binary_arrays[0]))))
# replace_101_202 = lambda test_list: list(map(int, re.sub('101', '909', ''.join(list(map(str, test_list))))))
# binary_arrays = np.array(list(map(replace_101_202, binary_arrays))) / 9
# print(binary_arrays)

[0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 2 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0
 1 0 0 1 1 2 2 1 2 1 1 0 0 0 0 1 2 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 1 1 0 1 0 0 1 1 1 1 2 3 2 2 1 1 2 2 1 2 1 1 0 0 0 0 0 1 0 0 1 1 2 2 1 2 1
 1 0 0 0 0 1 2 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0
 1 2 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 2 1 1 2 2 3 3 2 3 2 2 1 1 1 1 2 3 2 2 1
 1 2 2 1 2 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 1 2 3 2 2 1 1 2 2 1 2
 1 1 0 0 0 0 0 1 0 0 1 1 2 2 1 2 1 1 0 0 0 0 1 2 1 1 0 0 1 1 0 1 0 0]


In [560]:
zero_arrays = binary_arrays[occurences_arrays == 0]
display(zero_arrays[:10])
display((occurences_arrays == 0).sum())
one_arrays = binary_arrays[occurences_arrays == 1]
display(one_arrays[:10])
display((occurences_arrays == 1).sum())
two_arrays = binary_arrays[occurences_arrays == 2]
display(two_arrays[:10])
display((occurences_arrays == 2).sum())
three_arrays = binary_arrays[occurences_arrays == 3]
display((occurences_arrays == 3).sum())
four_arrays = binary_arrays[occurences_arrays == 4]
display((occurences_arrays == 4).sum())

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 0, 0]])

114

array([[0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1]])

98

array([[0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 1]])

38

6

0

In [561]:
# zero_X_train, zero_X_test, zero_y_train, zero_y_test = train_test_split(zero_arrays, np.zeros((len(zero_arrays),)), test_size=0.3, random_state=42)
# one_X_train, one_X_test, one_y_train, one_y_test = train_test_split(one_arrays, np.ones((len(one_arrays))), test_size=0.3, random_state=42)
# two_X_train, two_X_test, two_y_train, two_y_test = train_test_split(two_arrays, np.ones((len(two_arrays))), test_size=0.3, random_state=42)
# three_X_train, three_X_test, three_y_train, three_y_test = train_test_split(three_arrays, np.ones((len(three_arrays))), test_size=0.3, random_state=42)
zero_X_train = zero_X_test = zero_arrays
zero_y_train = zero_y_test = np.zeros((len(zero_X_train)), dtype=int)
one_X_train = one_X_test = one_arrays
one_y_train = one_y_test = np.ones((len(one_X_train)), dtype=int)
two_X_train = two_X_test = two_arrays
two_y_train = two_y_test = np.ones((len(two_arrays)), dtype=int)

X_train = np.concatenate((zero_X_train, one_X_train), axis=0)
y_train = np.concatenate((zero_y_train, one_y_train), axis=0)
# X_train, y_train = shuffle(X_train, y_train, random_state=0)

X_test = np.concatenate((zero_X_test, one_X_test), axis=0)
y_test = np.concatenate((zero_y_test, one_y_test), axis=0)
# X_test, y_test = shuffle(X_train, y_train, random_state=0)

In [640]:
data = [[1,0,0,0,1,0,1,0],
        [1,1,0,1,0,0,0,0],
        [1,0,0,0,0,0,1,0],
        [0,1,0,0,0,1,0,0],
        [0,0,1,0,1,0,1,0],
        [0,0,0,0,0,0,1,0],
        [0,1,0,1,0,0,0,1],
        [1,0,0,0,0,0,0,1],
        [1,1,0,0,1,0,1,0],
        [1,1,0,1,0,0,1,1],
        [1,0,0,0,0,0,1,1],
        [0,1,0,0,0,1,1,0],
        [0,0,1,0,1,0,1,0],
        [0,1,0,0,0,1,0,0],
        [0,1,0,1,0,1,0,0],
        [1,0,0,0,0,0,1,1]]
labels = [1,1,0,0,1,0,1,0,1,1,0,0,1,0,1,0]

X_train = X_test = np.array(data)
y_train = y_test = np.array(labels)

In [666]:
data = [[0.8,0.2,0.1,0.05,1,0,1,0.05],
        [0.23,0.98,0,0.99,0.1,0.2,0.15,0.02],
        [0.7,0.1,0.2,0.3,0.21,0.1,0.8,0.2],
        [0.2,0.8,0.1,0.1,0,0.9,0.15,0.12],
        [0,0.2,0.95,0.05,1,0,1,0.05],
        [0.2,0.2,0.2,0.2,0.01,0.2,0.8,0.1],
        [0.1,1,0,1,0.1,0.15,0.2,1],
        [1,0.11,0.32,0.1,0.001,0.02,0.05,0.85],
        [0.2,0.68,0.02,0.08,1,0,1,0.02],
        [0.98,1,0,1,0.01,0.02,0.75,0.1],
        [0.32,0.2,0.1,0.2,0.15,0.01,0.25,0.36],
        [0.08,0.5,0.12,0.01,0.1,0.05,0.76,0.2],
        [0.12,0.32,0.34,0.12,0.68,0.64,0.55,0.44],
        [0.01,0.97,0.01,0.98,0.1,0.2,0.1,0.01],
        [0,1,0.12,0.98,0.01,0.96,0.01,0.02],
        [0.88,0.2,0.2,0.1,0.01,0.01,0.7,0.7]]
labels = [1,1,0,0,1,0,1,0,1,1,0,0,0,1,1,0]

X_train = X_test = np.array(data)
y_train = y_test = np.array(labels)

In [667]:
display(X_train)
display(y_train)

array([[0.8  , 0.2  , 0.1  , 0.05 , 1.   , 0.   , 1.   , 0.05 ],
       [0.23 , 0.98 , 0.   , 0.99 , 0.1  , 0.2  , 0.15 , 0.02 ],
       [0.7  , 0.1  , 0.2  , 0.3  , 0.21 , 0.1  , 0.8  , 0.2  ],
       [0.2  , 0.8  , 0.1  , 0.1  , 0.   , 0.9  , 0.15 , 0.12 ],
       [0.   , 0.2  , 0.95 , 0.05 , 1.   , 0.   , 1.   , 0.05 ],
       [0.2  , 0.2  , 0.2  , 0.2  , 0.01 , 0.2  , 0.8  , 0.1  ],
       [0.1  , 1.   , 0.   , 1.   , 0.1  , 0.15 , 0.2  , 1.   ],
       [1.   , 0.11 , 0.32 , 0.1  , 0.001, 0.02 , 0.05 , 0.85 ],
       [0.2  , 0.68 , 0.02 , 0.08 , 1.   , 0.   , 1.   , 0.02 ],
       [0.98 , 1.   , 0.   , 1.   , 0.01 , 0.02 , 0.75 , 0.1  ],
       [0.32 , 0.2  , 0.1  , 0.2  , 0.15 , 0.01 , 0.25 , 0.36 ],
       [0.08 , 0.5  , 0.12 , 0.01 , 0.1  , 0.05 , 0.76 , 0.2  ],
       [0.12 , 0.32 , 0.34 , 0.12 , 0.68 , 0.64 , 0.55 , 0.44 ],
       [0.01 , 0.97 , 0.01 , 0.98 , 0.1  , 0.2  , 0.1  , 0.01 ],
       [0.   , 1.   , 0.12 , 0.98 , 0.01 , 0.96 , 0.01 , 0.02 ],
       [0.88 , 0.2  , 0.2

array([1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0])

In [668]:
CONVOLUTION_OUTPUT_LEN = LENGTH - FILTER_LENGTH + 1
POOLING_SIZE = 4
POOLING_OUTPUT_LEN = math.ceil(CONVOLUTION_OUTPUT_LEN / POOLING_SIZE)

model = dy.ParameterCollection()
conv_filter = model.add_parameters(FILTER_LENGTH)
conv_bias = model.add_parameters(1)
# conv_filter = model.add_parameters(FILTER_LENGTH, init='uniform', scale=1)

dense_params = model.add_parameters(POOLING_OUTPUT_LEN)
dense_bias = model.add_parameters(1)
trainer = dy.AdamTrainer(model, alpha=0.01)


def renew():
    dy.renew_cg()

    # trainer = dy.SimpleSGDTrainer(model, learning_rate=0.001)
    x = dy.vecInput(LENGTH)
    y = dy.scalarInput(0)

    convoluted = [0 for _ in range(CONVOLUTION_OUTPUT_LEN)]
    for i in range(CONVOLUTION_OUTPUT_LEN):
        convoluted[i] = (dy.transpose(conv_filter) * x[i:i+FILTER_LENGTH])[0] + conv_bias

    pooled = [0 for _ in range(POOLING_OUTPUT_LEN)]
    for i in range(POOLING_OUTPUT_LEN):
        pooled[i] = np.mean(convoluted[POOLING_SIZE*i:POOLING_SIZE*(i+1)])
    y_pred = dy.tanh(np.dot(pooled, dense_params.as_array())
                         + dense_bias)

    pooled = np.mean(convoluted)
    y_pred = dy.logistic(pooled)

    loss = dy.binary_log_loss(y_pred, y)
    
    return trainer, x, y, convoluted, pooled, y_pred, loss


def train(iters: int):
    predicted = []
    activations = []
    misclass = 0
    mloss = 0.0
    perfect_iteration = None

    for i in range(iters):
        trainer, x, y, convoluted, pooled, y_pred, loss = renew()
        mloss = 0.0
        misclass = 0
        for j in range(len(X_train)):
            x.set(X_train[j])
            y.set(y_train[j])
            pred = 1 if y_pred.value() > 0.5 else 0
            
            if (i + 1) % iters == 0:
                predicted.append(pred)
                activations.append(y_pred.value())

            # print(loss.scalar_value())
            if pred != int(y.value()):
                misclass += 1
                

            mloss += loss.scalar_value()
            loss.backward()
            trainer.update()
            
        mloss /= len(X_train)
        
        if (i+1) % 200 == 0:
            print(conv_filter.value())
            print(conv_bias.value())
            print(f'{i+1}/{iters}, loss: {mloss}, misclassified: {misclass}/{len(X_train)}')
        
        if perfect_iteration is None and misclass == 0:
            perfect_iteration = i + 1
        if (i + 1) % iters == 0:
            print(conv_filter.value())
            print("loss: %0.9f" % mloss)
            print(f'{misclass}/{len(X_train)} Missclassified')
            print('perfect_iteration', perfect_iteration)


    filter_weights = conv_filter.value()
    return misclass, predicted, filter_weights, mloss, activations, perfect_iteration



In [669]:
m, pr, fw, l, act, pit = train(10000)

[2.8180980682373047, 4.259247779846191, 0.8648182153701782]
-2.5686323642730713
200/10000, loss: 0.44698005449026823, misclassified: 2/16
[5.432982444763184, 6.911345481872559, 0.4804040491580963]
-4.320301055908203
400/10000, loss: 0.3530684425495565, misclassified: 2/16
[7.3145952224731445, 8.800163269042969, -0.08903441578149796]
-5.500290393829346
600/10000, loss: 0.31126625067554414, misclassified: 2/16
[8.738015174865723, 10.251307487487793, -0.7078465223312378]
-6.352838039398193
800/10000, loss: 0.2883445991901681, misclassified: 2/16
[9.868326187133789, 11.438785552978516, -1.3192758560180664]
-7.011061191558838
1000/10000, loss: 0.27377153385896236, misclassified: 2/16
[10.799363136291504, 12.45518970489502, -1.9012492895126343]
-7.546363830566406
1200/10000, loss: 0.2635598561610095, misclassified: 2/16
[11.58694076538086, 13.352766036987305, -2.446089744567871]
-7.999035358428955
1400/10000, loss: 0.2559232509229332, misclassified: 2/16
[12.266558647155762, 14.1631469726562

In [670]:
test_predicted = []
misclass = 0
for j in range(len(X_test)):
    trainer, x, y, convoluted, pooled, y_pred, loss = renew()
    x.set(X_test[j])
    y.set(y_test[j])
    pred = 1 if y_pred.value() > 0.5 else 0

    if pred != int(y.value()):
        print(X_test[j])
        print(pred, y.value())
    test_predicted.append(pred)

    if pred != int(y.value()):
        misclass += 1

[0.12 0.32 0.34 0.12 0.68 0.64 0.55 0.44]
1 0.0
